### ISSUE TITLE
where do i get the vrc libraries?

### ISSUE THREAD

**Issue by FireC123** [A5-/VRChat-Mod#7]
i cant seem to find the vrc libraries used in the code

**Comment by FireC123** [comment]
nevermind i figured it out you can find them in VRChat\VRChat_Data\Managed

**Comment by SkyeQuake** [comment]
iv been trying to do it but i dont understand any help? like what i acctualy need to do

**Comment by nynch** [comment]
1. Open Vrchat.sln in Visual Studio
2. In the Solution Explorer tab on the right-hand side, right-click References and take note of the references under the tab
3. Click Add References
4. Click the Browse tab and then click the Browse button at the bottom of the page
5. Navigate to VRChat\VRChat_Data\Managed directory from your VRChat directory, and select the specified .dll's
6. Press OK. Click the Build tab and select Build VRChat
7. VRCheat.dll will be in the folder you extracted

**Comment by SkyeQuake** [comment]
Omg thank you soo much ^^
